/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.3.0-18+deb9u1 -O2 -fdebug-prefix-map=/build/yosys-XOsRIM/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "rtl/GCD.v:1" *)
module GCD(clock, reset, io_value1, io_value2, io_loadingValues, io_outputGCD, io_outputValid);
  (* src = "rtl/GCD.v:68" *)
  wire [15:0] _000_;
  (* src = "rtl/GCD.v:68" *)
  wire [15:0] _001_;
  wire [7:0] _002_;
  wire [3:0] _003_;
  wire [1:0] _004_;
  wire [7:0] _005_;
  wire [3:0] _006_;
  wire [1:0] _007_;
  wire _008_;
  wire [15:0] _009_;
  wire [15:0] _010_;
  (* src = "<techmap.v>:258" *)
  wire [15:0] _011_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [15:0] _012_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [15:0] _013_;
  wire [15:0] _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  (* src = "<techmap.v>:258" *)
  wire [16:0] _018_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [16:0] _019_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [16:0] _020_;
  wire [16:0] _021_;
  (* src = "<techmap.v>:260" *)
  wire [15:0] _022_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _023_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _024_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _025_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _026_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _027_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _028_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _029_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _030_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _031_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _032_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _033_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _034_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _035_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _036_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _037_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _038_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _039_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _040_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _041_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _042_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _043_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _044_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _045_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _046_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _047_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _048_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _049_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _050_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _051_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _052_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _053_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _054_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _055_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _056_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _057_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _058_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _059_;
  (* src = "<techmap.v>:260" *)
  wire [16:0] _060_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _061_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _062_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _063_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _064_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _065_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _066_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _067_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _068_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _069_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _070_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _071_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _072_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _073_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _074_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _075_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _076_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _077_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _078_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _079_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _080_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _081_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _082_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _083_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _084_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _085_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _086_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _087_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _088_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _089_;
  (* src = "<techmap.v>:260|<techmap.v>:229" *)
  wire _090_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _091_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _092_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _093_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _094_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _095_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _096_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _097_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _098_;
  (* src = "rtl/GCD.v:15" *)
  wire [16:0] _T_18;
  (* src = "rtl/GCD.v:16" *)
  wire [16:0] _T_19;
  (* src = "rtl/GCD.v:17" *)
  wire [15:0] _T_20;
  (* src = "rtl/GCD.v:18" *)
  wire [16:0] _T_21;
  (* src = "rtl/GCD.v:19" *)
  wire [16:0] _T_22;
  (* src = "rtl/GCD.v:20" *)
  wire [15:0] _T_23;
  (* src = "rtl/GCD.v:2" *)
  input clock;
  (* src = "rtl/GCD.v:6" *)
  input io_loadingValues;
  (* src = "rtl/GCD.v:7" *)
  output [15:0] io_outputGCD;
  (* src = "rtl/GCD.v:8" *)
  output io_outputValid;
  (* src = "rtl/GCD.v:4" *)
  input [15:0] io_value1;
  (* src = "rtl/GCD.v:5" *)
  input [15:0] io_value2;
  (* src = "rtl/GCD.v:3" *)
  input reset;
  (* src = "rtl/GCD.v:10" *)
  reg [15:0] x;
  (* src = "rtl/GCD.v:12" *)
  reg [15:0] y;
  assign _002_[0] = _013_[0] & _014_[1];
  assign _003_[0] = _002_[0] & _002_[1];
  assign _004_[0] = _003_[0] & _003_[1];
  assign _016_ = _004_[0] & _004_[1];
  assign _008_ = _007_[0] |(* src = "rtl/GCD.v:33" *)  _007_[1];
  assign _005_[0] = y[0] |(* src = "rtl/GCD.v:33" *)  y[1];
  assign _005_[1] = y[2] |(* src = "rtl/GCD.v:33" *)  y[3];
  assign _005_[2] = y[4] |(* src = "rtl/GCD.v:33" *)  y[5];
  assign _005_[3] = y[6] |(* src = "rtl/GCD.v:33" *)  y[7];
  assign _005_[4] = y[8] |(* src = "rtl/GCD.v:33" *)  y[9];
  assign _005_[5] = y[10] |(* src = "rtl/GCD.v:33" *)  y[11];
  assign _005_[6] = y[12] |(* src = "rtl/GCD.v:33" *)  y[13];
  assign _005_[7] = y[14] |(* src = "rtl/GCD.v:33" *)  y[15];
  assign _006_[0] = _005_[0] |(* src = "rtl/GCD.v:33" *)  _005_[1];
  assign _006_[1] = _005_[2] |(* src = "rtl/GCD.v:33" *)  _005_[3];
  assign _006_[2] = _005_[4] |(* src = "rtl/GCD.v:33" *)  _005_[5];
  assign _006_[3] = _005_[6] |(* src = "rtl/GCD.v:33" *)  _005_[7];
  assign _007_[0] = _006_[0] |(* src = "rtl/GCD.v:33" *)  _006_[1];
  assign _007_[1] = _006_[2] |(* src = "rtl/GCD.v:33" *)  _006_[3];
  assign io_outputValid = ~(* src = "rtl/GCD.v:33" *) _008_;
  assign _009_[0] = _017_ ? (* src = "rtl/GCD.v:79" *) _T_21[0] : y[0];
  assign _009_[1] = _017_ ? (* src = "rtl/GCD.v:79" *) _T_21[1] : y[1];
  assign _009_[2] = _017_ ? (* src = "rtl/GCD.v:79" *) _T_21[2] : y[2];
  assign _009_[3] = _017_ ? (* src = "rtl/GCD.v:79" *) _T_21[3] : y[3];
  assign _009_[4] = _017_ ? (* src = "rtl/GCD.v:79" *) _T_21[4] : y[4];
  assign _009_[5] = _017_ ? (* src = "rtl/GCD.v:79" *) _T_21[5] : y[5];
  assign _009_[6] = _017_ ? (* src = "rtl/GCD.v:79" *) _T_21[6] : y[6];
  assign _009_[7] = _017_ ? (* src = "rtl/GCD.v:79" *) _T_21[7] : y[7];
  assign _009_[8] = _017_ ? (* src = "rtl/GCD.v:79" *) _T_21[8] : y[8];
  assign _009_[9] = _017_ ? (* src = "rtl/GCD.v:79" *) _T_21[9] : y[9];
  assign _009_[10] = _017_ ? (* src = "rtl/GCD.v:79" *) _T_21[10] : y[10];
  assign _009_[11] = _017_ ? (* src = "rtl/GCD.v:79" *) _T_21[11] : y[11];
  assign _009_[12] = _017_ ? (* src = "rtl/GCD.v:79" *) _T_21[12] : y[12];
  assign _009_[13] = _017_ ? (* src = "rtl/GCD.v:79" *) _T_21[13] : y[13];
  assign _009_[14] = _017_ ? (* src = "rtl/GCD.v:79" *) _T_21[14] : y[14];
  assign _009_[15] = _017_ ? (* src = "rtl/GCD.v:79" *) _T_21[15] : y[15];
  assign _001_[0] = io_loadingValues ? (* src = "rtl/GCD.v:76" *) io_value2[0] : _009_[0];
  assign _001_[1] = io_loadingValues ? (* src = "rtl/GCD.v:76" *) io_value2[1] : _009_[1];
  assign _001_[2] = io_loadingValues ? (* src = "rtl/GCD.v:76" *) io_value2[2] : _009_[2];
  assign _001_[3] = io_loadingValues ? (* src = "rtl/GCD.v:76" *) io_value2[3] : _009_[3];
  assign _001_[4] = io_loadingValues ? (* src = "rtl/GCD.v:76" *) io_value2[4] : _009_[4];
  assign _001_[5] = io_loadingValues ? (* src = "rtl/GCD.v:76" *) io_value2[5] : _009_[5];
  assign _001_[6] = io_loadingValues ? (* src = "rtl/GCD.v:76" *) io_value2[6] : _009_[6];
  assign _001_[7] = io_loadingValues ? (* src = "rtl/GCD.v:76" *) io_value2[7] : _009_[7];
  assign _001_[8] = io_loadingValues ? (* src = "rtl/GCD.v:76" *) io_value2[8] : _009_[8];
  assign _001_[9] = io_loadingValues ? (* src = "rtl/GCD.v:76" *) io_value2[9] : _009_[9];
  assign _001_[10] = io_loadingValues ? (* src = "rtl/GCD.v:76" *) io_value2[10] : _009_[10];
  assign _001_[11] = io_loadingValues ? (* src = "rtl/GCD.v:76" *) io_value2[11] : _009_[11];
  assign _001_[12] = io_loadingValues ? (* src = "rtl/GCD.v:76" *) io_value2[12] : _009_[12];
  assign _001_[13] = io_loadingValues ? (* src = "rtl/GCD.v:76" *) io_value2[13] : _009_[13];
  assign _001_[14] = io_loadingValues ? (* src = "rtl/GCD.v:76" *) io_value2[14] : _009_[14];
  assign _001_[15] = io_loadingValues ? (* src = "rtl/GCD.v:76" *) io_value2[15] : _009_[15];
  assign _010_[0] = _017_ ? (* src = "rtl/GCD.v:72" *) x[0] : _T_18[0];
  assign _010_[1] = _017_ ? (* src = "rtl/GCD.v:72" *) x[1] : _T_18[1];
  assign _010_[2] = _017_ ? (* src = "rtl/GCD.v:72" *) x[2] : _T_18[2];
  assign _010_[3] = _017_ ? (* src = "rtl/GCD.v:72" *) x[3] : _T_18[3];
  assign _010_[4] = _017_ ? (* src = "rtl/GCD.v:72" *) x[4] : _T_18[4];
  assign _010_[5] = _017_ ? (* src = "rtl/GCD.v:72" *) x[5] : _T_18[5];
  assign _010_[6] = _017_ ? (* src = "rtl/GCD.v:72" *) x[6] : _T_18[6];
  assign _010_[7] = _017_ ? (* src = "rtl/GCD.v:72" *) x[7] : _T_18[7];
  assign _010_[8] = _017_ ? (* src = "rtl/GCD.v:72" *) x[8] : _T_18[8];
  assign _010_[9] = _017_ ? (* src = "rtl/GCD.v:72" *) x[9] : _T_18[9];
  assign _010_[10] = _017_ ? (* src = "rtl/GCD.v:72" *) x[10] : _T_18[10];
  assign _010_[11] = _017_ ? (* src = "rtl/GCD.v:72" *) x[11] : _T_18[11];
  assign _010_[12] = _017_ ? (* src = "rtl/GCD.v:72" *) x[12] : _T_18[12];
  assign _010_[13] = _017_ ? (* src = "rtl/GCD.v:72" *) x[13] : _T_18[13];
  assign _010_[14] = _017_ ? (* src = "rtl/GCD.v:72" *) x[14] : _T_18[14];
  assign _010_[15] = _017_ ? (* src = "rtl/GCD.v:72" *) x[15] : _T_18[15];
  assign _000_[0] = io_loadingValues ? (* src = "rtl/GCD.v:69" *) io_value1[0] : _010_[0];
  assign _000_[1] = io_loadingValues ? (* src = "rtl/GCD.v:69" *) io_value1[1] : _010_[1];
  assign _000_[2] = io_loadingValues ? (* src = "rtl/GCD.v:69" *) io_value1[2] : _010_[2];
  assign _000_[3] = io_loadingValues ? (* src = "rtl/GCD.v:69" *) io_value1[3] : _010_[3];
  assign _000_[4] = io_loadingValues ? (* src = "rtl/GCD.v:69" *) io_value1[4] : _010_[4];
  assign _000_[5] = io_loadingValues ? (* src = "rtl/GCD.v:69" *) io_value1[5] : _010_[5];
  assign _000_[6] = io_loadingValues ? (* src = "rtl/GCD.v:69" *) io_value1[6] : _010_[6];
  assign _000_[7] = io_loadingValues ? (* src = "rtl/GCD.v:69" *) io_value1[7] : _010_[7];
  assign _000_[8] = io_loadingValues ? (* src = "rtl/GCD.v:69" *) io_value1[8] : _010_[8];
  assign _000_[9] = io_loadingValues ? (* src = "rtl/GCD.v:69" *) io_value1[9] : _010_[9];
  assign _000_[10] = io_loadingValues ? (* src = "rtl/GCD.v:69" *) io_value1[10] : _010_[10];
  assign _000_[11] = io_loadingValues ? (* src = "rtl/GCD.v:69" *) io_value1[11] : _010_[11];
  assign _000_[12] = io_loadingValues ? (* src = "rtl/GCD.v:69" *) io_value1[12] : _010_[12];
  assign _000_[13] = io_loadingValues ? (* src = "rtl/GCD.v:69" *) io_value1[13] : _010_[13];
  assign _000_[14] = io_loadingValues ? (* src = "rtl/GCD.v:69" *) io_value1[14] : _010_[14];
  assign _000_[15] = io_loadingValues ? (* src = "rtl/GCD.v:69" *) io_value1[15] : _010_[15];
  assign _015_ = ~_012_[15];
  assign _011_[14] = ~(* src = "<techmap.v>:258" *) y[14];
  assign _011_[0] = ~(* src = "<techmap.v>:258" *) y[0];
  assign _011_[1] = ~(* src = "<techmap.v>:258" *) y[1];
  assign _011_[2] = ~(* src = "<techmap.v>:258" *) y[2];
  assign _011_[3] = ~(* src = "<techmap.v>:258" *) y[3];
  assign _011_[4] = ~(* src = "<techmap.v>:258" *) y[4];
  assign _011_[5] = ~(* src = "<techmap.v>:258" *) y[5];
  assign _011_[6] = ~(* src = "<techmap.v>:258" *) y[6];
  assign _011_[7] = ~(* src = "<techmap.v>:258" *) y[7];
  assign _011_[8] = ~(* src = "<techmap.v>:258" *) y[8];
  assign _011_[9] = ~(* src = "<techmap.v>:258" *) y[9];
  assign _011_[10] = ~(* src = "<techmap.v>:258" *) y[10];
  assign _011_[11] = ~(* src = "<techmap.v>:258" *) y[11];
  assign _011_[12] = ~(* src = "<techmap.v>:258" *) y[12];
  assign _011_[13] = ~(* src = "<techmap.v>:258" *) y[13];
  assign _011_[15] = ~(* src = "<techmap.v>:258" *) y[15];
  assign _018_[0] = ~(* src = "<techmap.v>:258" *) x[0];
  assign _018_[1] = ~(* src = "<techmap.v>:258" *) x[1];
  assign _018_[2] = ~(* src = "<techmap.v>:258" *) x[2];
  assign _018_[3] = ~(* src = "<techmap.v>:258" *) x[3];
  assign _018_[4] = ~(* src = "<techmap.v>:258" *) x[4];
  assign _018_[5] = ~(* src = "<techmap.v>:258" *) x[5];
  assign _018_[6] = ~(* src = "<techmap.v>:258" *) x[6];
  assign _018_[7] = ~(* src = "<techmap.v>:258" *) x[7];
  assign _018_[8] = ~(* src = "<techmap.v>:258" *) x[8];
  assign _018_[9] = ~(* src = "<techmap.v>:258" *) x[9];
  assign _018_[10] = ~(* src = "<techmap.v>:258" *) x[10];
  assign _018_[11] = ~(* src = "<techmap.v>:258" *) x[11];
  assign _018_[12] = ~(* src = "<techmap.v>:258" *) x[12];
  assign _018_[13] = ~(* src = "<techmap.v>:258" *) x[13];
  assign _018_[14] = ~(* src = "<techmap.v>:258" *) x[14];
  assign _018_[15] = ~(* src = "<techmap.v>:258" *) x[15];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      x[0] <= _000_[0];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      x[1] <= _000_[1];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      x[2] <= _000_[2];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      x[3] <= _000_[3];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      x[4] <= _000_[4];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      x[5] <= _000_[5];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      x[6] <= _000_[6];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      x[7] <= _000_[7];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      x[8] <= _000_[8];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      x[9] <= _000_[9];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      x[10] <= _000_[10];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      x[11] <= _000_[11];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      x[12] <= _000_[12];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      x[13] <= _000_[13];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      x[14] <= _000_[14];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      x[15] <= _000_[15];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      y[0] <= _001_[0];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      y[1] <= _001_[1];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      y[2] <= _001_[2];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      y[3] <= _001_[3];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      y[4] <= _001_[4];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      y[5] <= _001_[5];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      y[6] <= _001_[6];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      y[7] <= _001_[7];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      y[8] <= _001_[8];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      y[9] <= _001_[9];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      y[10] <= _001_[10];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      y[11] <= _001_[11];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      y[12] <= _001_[12];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      y[13] <= _001_[13];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      y[14] <= _001_[14];
  (* src = "rtl/GCD.v:68" *)
  always @(posedge clock)
      y[15] <= _001_[15];
  assign _017_ = _015_ | _016_;
  assign _013_[0] = x[0] ^(* src = "<techmap.v>:262" *)  _011_[0];
  assign _014_[1] = x[1] ^(* src = "<techmap.v>:262" *)  _011_[1];
  assign _014_[2] = x[2] ^(* src = "<techmap.v>:262" *)  _011_[2];
  assign _014_[3] = x[3] ^(* src = "<techmap.v>:262" *)  _011_[3];
  assign _014_[4] = x[4] ^(* src = "<techmap.v>:262" *)  _011_[4];
  assign _014_[5] = x[5] ^(* src = "<techmap.v>:262" *)  _011_[5];
  assign _014_[6] = x[6] ^(* src = "<techmap.v>:262" *)  _011_[6];
  assign _014_[7] = x[7] ^(* src = "<techmap.v>:262" *)  _011_[7];
  assign _014_[8] = x[8] ^(* src = "<techmap.v>:262" *)  _011_[8];
  assign _014_[9] = x[9] ^(* src = "<techmap.v>:262" *)  _011_[9];
  assign _014_[10] = x[10] ^(* src = "<techmap.v>:262" *)  _011_[10];
  assign _014_[11] = x[11] ^(* src = "<techmap.v>:262" *)  _011_[11];
  assign _014_[12] = x[12] ^(* src = "<techmap.v>:262" *)  _011_[12];
  assign _014_[13] = x[13] ^(* src = "<techmap.v>:262" *)  _011_[13];
  assign _014_[14] = x[14] ^(* src = "<techmap.v>:262" *)  _011_[14];
  assign _014_[15] = x[15] ^(* src = "<techmap.v>:262" *)  _011_[15];
  assign _T_18[0] = _013_[0] ^(* src = "<techmap.v>:263" *)  1'b1;
  assign _T_18[1] = _014_[1] ^(* src = "<techmap.v>:263" *)  _012_[0];
  assign _T_18[2] = _014_[2] ^(* src = "<techmap.v>:263" *)  _012_[1];
  assign _T_18[3] = _014_[3] ^(* src = "<techmap.v>:263" *)  _012_[2];
  assign _T_18[4] = _014_[4] ^(* src = "<techmap.v>:263" *)  _012_[3];
  assign _T_18[5] = _014_[5] ^(* src = "<techmap.v>:263" *)  _012_[4];
  assign _T_18[6] = _014_[6] ^(* src = "<techmap.v>:263" *)  _012_[5];
  assign _T_18[7] = _014_[7] ^(* src = "<techmap.v>:263" *)  _012_[6];
  assign _T_18[8] = _014_[8] ^(* src = "<techmap.v>:263" *)  _012_[7];
  assign _T_18[9] = _014_[9] ^(* src = "<techmap.v>:263" *)  _012_[8];
  assign _T_18[10] = _014_[10] ^(* src = "<techmap.v>:263" *)  _012_[9];
  assign _T_18[11] = _014_[11] ^(* src = "<techmap.v>:263" *)  _012_[10];
  assign _T_18[12] = _014_[12] ^(* src = "<techmap.v>:263" *)  _012_[11];
  assign _T_18[13] = _014_[13] ^(* src = "<techmap.v>:263" *)  _012_[12];
  assign _T_18[14] = _014_[14] ^(* src = "<techmap.v>:263" *)  _012_[13];
  assign _T_18[15] = _014_[15] ^(* src = "<techmap.v>:263" *)  _012_[14];
  assign _022_[0] = x[0] &(* src = "<techmap.v>:260" *)  _011_[0];
  assign _022_[1] = x[1] &(* src = "<techmap.v>:260" *)  _011_[1];
  assign _022_[2] = x[2] &(* src = "<techmap.v>:260" *)  _011_[2];
  assign _022_[3] = x[3] &(* src = "<techmap.v>:260" *)  _011_[3];
  assign _022_[4] = x[4] &(* src = "<techmap.v>:260" *)  _011_[4];
  assign _022_[5] = x[5] &(* src = "<techmap.v>:260" *)  _011_[5];
  assign _022_[6] = x[6] &(* src = "<techmap.v>:260" *)  _011_[6];
  assign _022_[7] = x[7] &(* src = "<techmap.v>:260" *)  _011_[7];
  assign _022_[8] = x[8] &(* src = "<techmap.v>:260" *)  _011_[8];
  assign _022_[9] = x[9] &(* src = "<techmap.v>:260" *)  _011_[9];
  assign _022_[10] = x[10] &(* src = "<techmap.v>:260" *)  _011_[10];
  assign _022_[11] = x[11] &(* src = "<techmap.v>:260" *)  _011_[11];
  assign _022_[12] = x[12] &(* src = "<techmap.v>:260" *)  _011_[12];
  assign _022_[13] = x[13] &(* src = "<techmap.v>:260" *)  _011_[13];
  assign _022_[14] = x[14] &(* src = "<techmap.v>:260" *)  _011_[14];
  assign _022_[15] = x[15] &(* src = "<techmap.v>:260" *)  _011_[15];
  assign _020_[0] = y[0] ^(* src = "<techmap.v>:262" *)  _018_[0];
  assign _021_[1] = y[1] ^(* src = "<techmap.v>:262" *)  _018_[1];
  assign _021_[2] = y[2] ^(* src = "<techmap.v>:262" *)  _018_[2];
  assign _021_[3] = y[3] ^(* src = "<techmap.v>:262" *)  _018_[3];
  assign _021_[4] = y[4] ^(* src = "<techmap.v>:262" *)  _018_[4];
  assign _021_[5] = y[5] ^(* src = "<techmap.v>:262" *)  _018_[5];
  assign _021_[6] = y[6] ^(* src = "<techmap.v>:262" *)  _018_[6];
  assign _021_[7] = y[7] ^(* src = "<techmap.v>:262" *)  _018_[7];
  assign _021_[8] = y[8] ^(* src = "<techmap.v>:262" *)  _018_[8];
  assign _021_[9] = y[9] ^(* src = "<techmap.v>:262" *)  _018_[9];
  assign _021_[10] = y[10] ^(* src = "<techmap.v>:262" *)  _018_[10];
  assign _021_[11] = y[11] ^(* src = "<techmap.v>:262" *)  _018_[11];
  assign _021_[12] = y[12] ^(* src = "<techmap.v>:262" *)  _018_[12];
  assign _021_[13] = y[13] ^(* src = "<techmap.v>:262" *)  _018_[13];
  assign _021_[14] = y[14] ^(* src = "<techmap.v>:262" *)  _018_[14];
  assign _021_[15] = y[15] ^(* src = "<techmap.v>:262" *)  _018_[15];
  assign _T_21[0] = _020_[0] ^(* src = "<techmap.v>:263" *)  1'b1;
  assign _T_21[1] = _021_[1] ^(* src = "<techmap.v>:263" *)  _019_[0];
  assign _T_21[2] = _021_[2] ^(* src = "<techmap.v>:263" *)  _019_[1];
  assign _T_21[3] = _021_[3] ^(* src = "<techmap.v>:263" *)  _019_[2];
  assign _T_21[4] = _021_[4] ^(* src = "<techmap.v>:263" *)  _019_[3];
  assign _T_21[5] = _021_[5] ^(* src = "<techmap.v>:263" *)  _019_[4];
  assign _T_21[6] = _021_[6] ^(* src = "<techmap.v>:263" *)  _019_[5];
  assign _T_21[7] = _021_[7] ^(* src = "<techmap.v>:263" *)  _019_[6];
  assign _T_21[8] = _021_[8] ^(* src = "<techmap.v>:263" *)  _019_[7];
  assign _T_21[9] = _021_[9] ^(* src = "<techmap.v>:263" *)  _019_[8];
  assign _T_21[10] = _021_[10] ^(* src = "<techmap.v>:263" *)  _019_[9];
  assign _T_21[11] = _021_[11] ^(* src = "<techmap.v>:263" *)  _019_[10];
  assign _T_21[12] = _021_[12] ^(* src = "<techmap.v>:263" *)  _019_[11];
  assign _T_21[13] = _021_[13] ^(* src = "<techmap.v>:263" *)  _019_[12];
  assign _T_21[14] = _021_[14] ^(* src = "<techmap.v>:263" *)  _019_[13];
  assign _T_21[15] = _021_[15] ^(* src = "<techmap.v>:263" *)  _019_[14];
  assign _060_[0] = y[0] &(* src = "<techmap.v>:260" *)  _018_[0];
  assign _060_[1] = y[1] &(* src = "<techmap.v>:260" *)  _018_[1];
  assign _060_[2] = y[2] &(* src = "<techmap.v>:260" *)  _018_[2];
  assign _060_[3] = y[3] &(* src = "<techmap.v>:260" *)  _018_[3];
  assign _060_[4] = y[4] &(* src = "<techmap.v>:260" *)  _018_[4];
  assign _060_[5] = y[5] &(* src = "<techmap.v>:260" *)  _018_[5];
  assign _060_[6] = y[6] &(* src = "<techmap.v>:260" *)  _018_[6];
  assign _060_[7] = y[7] &(* src = "<techmap.v>:260" *)  _018_[7];
  assign _060_[8] = y[8] &(* src = "<techmap.v>:260" *)  _018_[8];
  assign _060_[9] = y[9] &(* src = "<techmap.v>:260" *)  _018_[9];
  assign _060_[10] = y[10] &(* src = "<techmap.v>:260" *)  _018_[10];
  assign _060_[11] = y[11] &(* src = "<techmap.v>:260" *)  _018_[11];
  assign _060_[12] = y[12] &(* src = "<techmap.v>:260" *)  _018_[12];
  assign _060_[13] = y[13] &(* src = "<techmap.v>:260" *)  _018_[13];
  assign _060_[14] = y[14] &(* src = "<techmap.v>:260" *)  _018_[14];
  assign _012_[15] = _059_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _037_;
  assign _012_[13] = _054_ |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _041_;
  assign _012_[6] = _022_[6] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _044_;
  assign _012_[8] = _022_[8] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _045_;
  assign _012_[10] = _022_[10] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _046_;
  assign _012_[12] = _022_[12] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _047_;
  assign _023_ = _014_[1] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _012_[0];
  assign _024_ = _014_[3] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _022_[2];
  assign _025_ = _014_[5] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _022_[4];
  assign _026_ = _014_[7] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _022_[6];
  assign _027_ = _014_[9] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _022_[8];
  assign _028_ = _014_[11] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _022_[10];
  assign _029_ = _014_[13] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _022_[12];
  assign _030_ = _014_[15] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _022_[14];
  assign _031_ = _002_[1] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _012_[1];
  assign _032_ = _002_[3] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _050_;
  assign _033_ = _002_[5] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _052_;
  assign _034_ = _002_[7] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _054_;
  assign _035_ = _003_[1] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _012_[3];
  assign _036_ = _003_[3] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _057_;
  assign _037_ = _004_[1] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _012_[7];
  assign _002_[1] = _014_[3] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _014_[2];
  assign _002_[2] = _014_[5] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _014_[4];
  assign _002_[3] = _014_[7] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _014_[6];
  assign _002_[4] = _014_[9] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _014_[8];
  assign _002_[5] = _014_[11] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _014_[10];
  assign _002_[6] = _014_[13] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _014_[12];
  assign _002_[7] = _014_[15] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _014_[14];
  assign _003_[1] = _002_[3] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _002_[2];
  assign _003_[2] = _002_[5] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _002_[4];
  assign _003_[3] = _002_[7] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _002_[6];
  assign _004_[1] = _003_[3] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _003_[2];
  assign _038_ = _003_[2] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _012_[7];
  assign _039_ = _002_[2] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _012_[3];
  assign _040_ = _002_[4] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _012_[7];
  assign _041_ = _002_[6] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _012_[11];
  assign _042_ = _014_[2] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _012_[1];
  assign _043_ = _014_[4] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _012_[3];
  assign _044_ = _014_[6] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _012_[5];
  assign _045_ = _014_[8] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _012_[7];
  assign _046_ = _014_[10] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _012_[9];
  assign _047_ = _014_[12] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _012_[11];
  assign _048_ = _014_[14] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _012_[13];
  assign _012_[0] = _022_[0] |(* src = "<techmap.v>:260|<techmap.v>:212" *)  _013_[0];
  assign _012_[1] = _022_[1] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _023_;
  assign _049_ = _022_[3] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _024_;
  assign _050_ = _022_[5] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _025_;
  assign _051_ = _022_[7] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _026_;
  assign _052_ = _022_[9] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _027_;
  assign _053_ = _022_[11] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _028_;
  assign _054_ = _022_[13] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _029_;
  assign _055_ = _022_[15] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _030_;
  assign _012_[3] = _049_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _031_;
  assign _056_ = _051_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _032_;
  assign _057_ = _053_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _033_;
  assign _058_ = _055_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _034_;
  assign _012_[7] = _056_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _035_;
  assign _059_ = _058_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _036_;
  assign _012_[11] = _057_ |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _038_;
  assign _012_[5] = _050_ |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _039_;
  assign _012_[9] = _052_ |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _040_;
  assign _012_[2] = _022_[2] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _042_;
  assign _012_[4] = _022_[4] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _043_;
  assign _012_[14] = _022_[14] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _048_;
  assign _061_ = _021_[1] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _019_[0];
  assign _062_ = _021_[3] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _060_[2];
  assign _063_ = _021_[5] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _060_[4];
  assign _064_ = _021_[7] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _060_[6];
  assign _065_ = _021_[9] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _060_[8];
  assign _066_ = _021_[11] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _060_[10];
  assign _067_ = _021_[13] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _060_[12];
  assign _068_ = _072_ &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _019_[1];
  assign _069_ = _074_ &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _092_;
  assign _070_ = _076_ &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _094_;
  assign _071_ = _078_ &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _019_[3];
  assign _072_ = _021_[3] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _021_[2];
  assign _073_ = _021_[5] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _021_[4];
  assign _074_ = _021_[7] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _021_[6];
  assign _075_ = _021_[9] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _021_[8];
  assign _076_ = _021_[11] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _021_[10];
  assign _077_ = _021_[13] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _021_[12];
  assign _078_ = _074_ &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _073_;
  assign _079_ = _076_ &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _075_;
  assign _080_ = _079_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _019_[7];
  assign _081_ = _073_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _019_[3];
  assign _082_ = _075_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _019_[7];
  assign _083_ = _077_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _019_[11];
  assign _084_ = _021_[2] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _019_[1];
  assign _085_ = _021_[4] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _019_[3];
  assign _086_ = _021_[6] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _019_[5];
  assign _087_ = _021_[8] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _019_[7];
  assign _088_ = _021_[10] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _019_[9];
  assign _089_ = _021_[12] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _019_[11];
  assign _090_ = _021_[14] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _019_[13];
  assign _019_[0] = _060_[0] |(* src = "<techmap.v>:260|<techmap.v>:212" *)  _020_[0];
  assign _019_[1] = _060_[1] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _061_;
  assign _091_ = _060_[3] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _062_;
  assign _092_ = _060_[5] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _063_;
  assign _093_ = _060_[7] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _064_;
  assign _094_ = _060_[9] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _065_;
  assign _095_ = _060_[11] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _066_;
  assign _096_ = _060_[13] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _067_;
  assign _019_[3] = _091_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _068_;
  assign _097_ = _093_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _069_;
  assign _098_ = _095_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _070_;
  assign _019_[7] = _097_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _071_;
  assign _019_[11] = _098_ |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _080_;
  assign _019_[5] = _092_ |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _081_;
  assign _019_[9] = _094_ |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _082_;
  assign _019_[13] = _096_ |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _083_;
  assign _019_[2] = _060_[2] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _084_;
  assign _019_[4] = _060_[4] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _085_;
  assign _019_[6] = _060_[6] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _086_;
  assign _019_[8] = _060_[8] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _087_;
  assign _019_[10] = _060_[10] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _088_;
  assign _019_[12] = _060_[12] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _089_;
  assign _019_[14] = _060_[14] |(* src = "<techmap.v>:260|<techmap.v>:229" *)  _090_;
  assign _T_19 = _T_18;
  assign _T_20 = _T_18[15:0];
  assign _T_22 = _T_21;
  assign _T_23 = _T_21[15:0];
  assign io_outputGCD = x;
endmodule
